AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app/index.handler
      Runtime: nodejs6.10
      Timeout: 60
      Policies: AmazonDynamoDBFullAccess
      Events:
        ApiEventSource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
    DependsOn: AppTable

  AppTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "timestamp"
          AttributeType: "N"
      KeySchema:
        -
          AttributeName:  "timestamp"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5